#!/usr/bin/env perl
use strict;

my $INSTANCE_VAR_NAME = 'KAFKA_INSTANCE_NAME';
my $ZK_NAMESPACE_VAR_NAME = 'KAFKA_ZK_NAMESPACE';

sub usage {
  print <<EOF;
  $0 zookeeper connectstr
  $0 zookeeper wait
  $0 cluster boostrapstr
  $0 cluster wait
EOF
  exit(1);
}

sub main {
  &usage unless @ARGV;
  my @args = @ARGV;
  my %cmds = (
    zookeeper => \&zookeeper,
    cluster => \&cluster
  );
  &dispatch(\%cmds, \@args);
}

sub dispatch {
  my ($cmds, $args) = @_;
  my $cmd = shift(@$args);
  &usage() unless exists $cmds->{$cmd};
  $cmds->{$cmd}->(@$args);
}

sub zookeeper {
  my @args = @_;
  my %cmds = (
    connectstr => \&zk_connect_str,
    wait => \&zk_wait
  );
  &dispatch(\%cmds, \@args);
}

sub zk_connect_str {
  print &zk_get_connect_str();
}

sub zk_wait {
  my @servers = &zk_get_servers();
  foreach my $svr (@servers) {
    my $zk_poll_cmd = "echo ruok | nc -w 2 $svr->{'host'} $svr->{'port'} | grep imok";
    print "Polling ZooKeeper Service ($zk_poll_cmd) ...";
    until (system($zk_poll_cmd) == 0) {
      print('.');
      sleep(2);
    };
    print "OK\n";
  }
}

sub cluster {
  my @args = @_;
  my %cmds = (
    boostrapstr => \&cluster_bootstrap_str,
    wait => \&cluster_wait
  );
  &dispatch(\%cmds, \@args);
}

sub cluster_bootstrap_str {
  print("BOOT\n");
}

sub cluster_wait {
  print("CLUSTER WAIT\n");
}

sub zk_get_connect_str {
  my @servers = &zk_get_servers();
  my @svr_strs = map { "$_->{'host'}:$_->{'port'}" } @servers;
  my $zk_path = $ENV{$ZK_NAMESPACE_VAR_NAME} || '/';
  return join(',', @svr_strs) . $zk_path;
}

sub zk_get_servers {
  die "Need to set $INSTANCE_VAR_NAME env var" unless exists $ENV{$INSTANCE_VAR_NAME};
  my $id = $ENV{$INSTANCE_VAR_NAME};
  my $zk_svc_var_prefix = uc("$id-zookeeper-");
  $zk_svc_var_prefix =~ tr/-/_/;
  my @servers = ();
  my $i = 1;
  do {
    my $host_var = "${zk_svc_var_prefix}${i}_SERVICE_HOST";
    die "Must set $host_var env var" unless exists $ENV{$host_var};
    my $client_port_var = "${zk_svc_var_prefix}${i}_SERVICE_PORT_CLIENT";
    die "Must set $client_port_var env var" unless exists $ENV{$client_port_var};
    push @servers, {host => $ENV{$host_var}, port => $ENV{$client_port_var}};
    $i += 1;
  } while (exists $ENV{"${zk_svc_var_prefix}${i}_SERVICE_HOST"});
  return @servers;
}

&main();

1;
